### ISSUE TITLE
Running Quinine without a Schema results in TypeError("Don't know how to join %s" % cls.__name__)

### ISSUE THREAD

**Issue by siddk** [krandiash/quinine#3]
Without a valid Schema provided, QuinineArgumentParser errors out.

Pretty sure this is the offending line (merge with None): https://github.com/krandiash/quinine/blob/master/quinine/common/argparse.py#L48

**Comment by krandiash** [comment]
I took your word for it and just updated the offending line -- pushed out a new release `0.2.2`, let me know if that works.
